### ISSUE TITLE
Switch repository to https://github.com/gbv/coli-conc.gbv.de/

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-conc-next#6]
With the launch, the repository should be moved to https://github.com/gbv/coli-conc.gbv.de/. Old content can be put into another branch.

**Comment by stefandesu** [comment]
I would suggest that we use the existing repo and move everything from here into that repo. We could rename the existing `master` branch to `old`, and put the data from here into the new `master` branch (or use the opportunity to choose a different name, such as `main`).

**Comment by stefandesu** [comment]
(After switching, we should also move remaining issues over, and then archive this repo.)
